print("Welcome to the tip calculator!")
total_bill = int(input("What was the total bill?\n"))
tip = int(input("How much tip would you like to give?\n"))
people = int(input("How many people to split the bill?\n"))
average_bill = ((total_bill + tip) / people)
print(f"Each person should pay: ${average_bill}")